CREATE TABLE IF NOT EXISTS kindofsport (
  id  BIGINT AUTO_INCREMENT PRIMARY KEY,
  name_kindofsport VARCHAR(1000) CHARACTER SET cp1251 NOT NULL
);
CREATE TABLE IF NOT EXISTS category (
  id  BIGINT AUTO_INCREMENT PRIMARY KEY,
  name_category VARCHAR(1000) CHARACTER SET cp1251 NOT NULL,
  kindofsport_id  BIGINT NOT NULL,
  FOREIGN KEY (kindofsport_id) REFERENCES kindofsport(id)
);
CREATE TABLE IF NOT EXISTS source (
  id  BIGINT AUTO_INCREMENT PRIMARY KEY,
  name_source VARCHAR(1000) CHARACTER SET cp1251  NOT NULL
);
CREATE TABLE IF NOT EXISTS news (
 id  BIGINT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(1000) CHARACTER SET cp1251   NOT NULL ,
 description VARCHAR(5000)  CHARACTER SET cp1251  NOT NULL ,
 url_to_source VARCHAR(1000) CHARACTER SET cp1251   NOT NULL ,
 url_img VARCHAR(1000) CHARACTER SET cp1251   NOT NULL ,
 publish_at VARCHAR(1000)  CHARACTER SET cp1251  NOT NULL ,
 source_id  BIGINT NOT NULL,
 category_id  BIGINT NOT NULL,
 FOREIGN KEY (source_id) REFERENCES source(id),
 FOREIGN KEY (category_id) REFERENCES category(id)
 );
CREATE TABLE IF NOT EXISTS comments (
  id  BIGINT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(1000) CHARACTER SET cp1251 NOT NULL,
  dateComment VARCHAR(1000) CHARACTER SET cp1251 NOT NULL,
  email VARCHAR(1000) CHARACTER SET cp1251 NOT NULL,
  news_id  BIGINT NOT NULL,
  FOREIGN KEY (news_id) REFERENCES news(id)
);