INSERT INTO source VALUES (1, 'fnk');
INSERT INTO source VALUES (2, 'sportbox');
INSERT INTO source VALUES (3, 'sports');
INSERT INTO source VALUES (4, 'championat');
INSERT INTO source VALUES (5, 'bloodandsweat');
INSERT INTO source VALUES (6, 'vsenabox');
INSERT INTO kindofsport VALUES (1,'football');
INSERT INTO kindofsport VALUES (2,'basketball');
INSERT INTO kindofsport VALUES (3,'volleyball');
INSERT INTO kindofsport VALUES (4,'hockey');
INSERT INTO kindofsport VALUES (5,'tennis');
INSERT INTO kindofsport VALUES (6,'mma');
INSERT INTO kindofsport VALUES (7,'biatlon');
INSERT INTO kindofsport VALUES (8,'boks');
INSERT INTO category VALUES (1, 'england',1);
INSERT INTO category VALUES (2, 'germany',1);
INSERT INTO category VALUES (3, 'spain',1);
INSERT INTO category VALUES (4, 'france',1);
INSERT INTO category VALUES (5, 'holland',1);
INSERT INTO category VALUES (6, 'nhl',4);
INSERT INTO category VALUES (7, 'khl',4);
INSERT INTO category VALUES (8, 'nba',2);
INSERT INTO category VALUES (9, 'vtb',2);
INSERT INTO category VALUES (10, 'russian',3);
INSERT INTO category VALUES (11, 'tennis',5);
INSERT INTO category VALUES (12, 'bellator',6);
INSERT INTO category VALUES (13, 'UFC',6);
INSERT INTO category VALUES (14, 'biatlon',7);
INSERT INTO category VALUES (15, 'box',8);
INSERT INTO category VALUES (16, 'eurocups',3);
INSERT INTO category VALUES (17, 'uefa_cup',1);
INSERT INTO category VALUES (18, 'league',1);

